name: Node JS Action
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Main
    runs-on: ${{ matrix.operating-system }}
    strategy:
        matrix:
          node-version: [10]
          operating-system: [ubuntu-latest]
    steps:
      - name: Prepare
        uses: actions/checkout@v1
      - name: Set Up Node JS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.java-version }}